### ISSUE TITLE
I want to contribute.

### ISSUE THREAD

**Issue by hiteshverse** [FORGEAR/GitHub-README-Showcase#17]

**Comment by manulthanura** [comment]
- [Fork the repository](https://github.com/FORGEAR/GitHub-README-Showcase/fork) - This will create a copy of the repository in your own GitHub account.
- Create a new branch - This will allow you to work on your changes without affecting the main repository.
- Add the README files - You want to contribute. You can do this by cloning the repository to your local machine, adding the files, and then pushing the changes to your forked repository.
- Submit a pull request - This will create a request for your changes to be merged into the main repository.
- Wait for your pull request to be reviewed - Your pull request will be reviewed by the repository owner. If there are any issues with your pull request, you will be notified via email.
- Celebrate - Your pull request has been merged into the main repository! Your changes will now be visible to everyone who visits the repository.
